version: "3"
services:
  main:
    image: "${REGISTRY:?}/${IMAGE_NAME:?}:${IMAGE_TAG:?}"
    restart: unless-stopped
    env_file: .env
    environment:
      GITHUB_SHA: "${GITHUB_SHA:-}"
      REDIS_HOST: "redis"
    volumes:
      - /home/github/userbot/data:/data
  redis:
    image: redis:7.0-alpine
    restart: unless-stopped
    volumes:
      - /home/github/userbot/redis:/data
