version: "3"
services:
  main:
    build: .
    image: evgfilim1/userbot:staging
    env_file: .env
    environment:
      REDIS_HOST: "redis"
    volumes:
      - ./.dockerdata/userbot:/data
    depends_on:
      - redis
  redis:
    image: redis:7.0-alpine
    volumes:
      - ./.dockerdata/redis:/data
