services:
  main:
    image: "${REGISTRY:?}/${IMAGE_NAME:?}:${IMAGE_TAG:?}"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 512M
    env_file: .env
    environment:
      GITHUB_SHA: "${GITHUB_SHA:-}"
      REDIS_HOST: "redis"
    volumes:
      - /home/github/userbot/data:/data
    depends_on:
      - redis
  redis:
    image: redis:7.0-alpine
    restart: unless-stopped
    volumes:
      - /home/github/userbot/redis:/data
